use crate::ffi;

#[allow(non_camel_case_types)]
#[derive(Eq, PartialEq, Copy, Clone, Debug)]
pub enum PacketSideDataType {
    Palette,
    NewExtraData,
    ParamChange,
    H263MbInfo,
    ReplayGain,
    DisplayMatrix,
    Stereo3d,
    AudioServiceType,
    QualityStats,
    FallbackTrack,
    CBPProperties,
    SkipSamples,
    JpDualMono,
    StringsMetadata,
    SubtitlePosition,
    MatroskaBlockAdditional,
    WebVTTIdentifier,
    WebVTTSettings,
    MetadataUpdate,
    MPEGTSStreamID,
    MasteringDisplayMetadata,
    DataSpherical,
    ContentLightLevel,
    A53CC,
    EncryptionInitInfo,
    EncryptionInfo,
    AFD,
    PRFT,
    ICC_PROFILE,
    DOVI_CONF,
    S12M_TIMECODE,
    DYNAMIC_HDR10_PLUS,
    DataNb
}

impl From<ffi::AVPacketSideDataType> for PacketSideDataType {
    fn from(value: ffi::AVPacketSideDataType) -> Self {
        match value {
            ffi::AVPacketSideDataType::AV_PKT_DATA_PALETTE => PacketSideDataType::Palette,
            ffi::AVPacketSideDataType::AV_PKT_DATA_NEW_EXTRADATA => PacketSideDataType::NewExtraData,
            ffi::AVPacketSideDataType::AV_PKT_DATA_PARAM_CHANGE => PacketSideDataType::ParamChange,
            ffi::AVPacketSideDataType::AV_PKT_DATA_H263_MB_INFO => PacketSideDataType::H263MbInfo,
            ffi::AVPacketSideDataType::AV_PKT_DATA_REPLAYGAIN => PacketSideDataType::ReplayGain,
            ffi::AVPacketSideDataType::AV_PKT_DATA_DISPLAYMATRIX => PacketSideDataType::DisplayMatrix,
            ffi::AVPacketSideDataType::AV_PKT_DATA_STEREO3D => PacketSideDataType::Stereo3d,
            ffi::AVPacketSideDataType::AV_PKT_DATA_AUDIO_SERVICE_TYPE => PacketSideDataType::AudioServiceType,
            ffi::AVPacketSideDataType::AV_PKT_DATA_QUALITY_STATS => PacketSideDataType::QualityStats,
            ffi::AVPacketSideDataType::AV_PKT_DATA_FALLBACK_TRACK => PacketSideDataType::FallbackTrack,
            ffi::AVPacketSideDataType::AV_PKT_DATA_CPB_PROPERTIES => PacketSideDataType::CBPProperties,
            ffi::AVPacketSideDataType::AV_PKT_DATA_SKIP_SAMPLES => PacketSideDataType::SkipSamples,
            ffi::AVPacketSideDataType::AV_PKT_DATA_JP_DUALMONO => PacketSideDataType::JpDualMono,
            ffi::AVPacketSideDataType::AV_PKT_DATA_STRINGS_METADATA => PacketSideDataType::StringsMetadata,
            ffi::AVPacketSideDataType::AV_PKT_DATA_SUBTITLE_POSITION => PacketSideDataType::SubtitlePosition,
            ffi::AVPacketSideDataType::AV_PKT_DATA_MATROSKA_BLOCKADDITIONAL => PacketSideDataType::MatroskaBlockAdditional,
            ffi::AVPacketSideDataType::AV_PKT_DATA_WEBVTT_IDENTIFIER => PacketSideDataType::WebVTTIdentifier,
            ffi::AVPacketSideDataType::AV_PKT_DATA_WEBVTT_SETTINGS => PacketSideDataType::WebVTTSettings,
            ffi::AVPacketSideDataType::AV_PKT_DATA_METADATA_UPDATE => PacketSideDataType::MetadataUpdate,
            ffi::AVPacketSideDataType::AV_PKT_DATA_MPEGTS_STREAM_ID => PacketSideDataType::MPEGTSStreamID,
            ffi::AVPacketSideDataType::AV_PKT_DATA_MASTERING_DISPLAY_METADATA => PacketSideDataType::MasteringDisplayMetadata,
            ffi::AVPacketSideDataType::AV_PKT_DATA_SPHERICAL => PacketSideDataType::DataSpherical,
            ffi::AVPacketSideDataType::AV_PKT_DATA_CONTENT_LIGHT_LEVEL => PacketSideDataType::ContentLightLevel,
            ffi::AVPacketSideDataType::AV_PKT_DATA_A53_CC => PacketSideDataType::A53CC,
            ffi::AVPacketSideDataType::AV_PKT_DATA_ENCRYPTION_INIT_INFO => PacketSideDataType::EncryptionInitInfo,
            ffi::AVPacketSideDataType::AV_PKT_DATA_ENCRYPTION_INFO => PacketSideDataType::EncryptionInfo,
            ffi::AVPacketSideDataType::AV_PKT_DATA_AFD => PacketSideDataType::AFD,
            ffi::AVPacketSideDataType::AV_PKT_DATA_PRFT => PacketSideDataType::PRFT,
            ffi::AVPacketSideDataType::AV_PKT_DATA_ICC_PROFILE => PacketSideDataType::ICC_PROFILE,
            ffi::AVPacketSideDataType::AV_PKT_DATA_DOVI_CONF => PacketSideDataType::DOVI_CONF,
            ffi::AVPacketSideDataType::AV_PKT_DATA_S12M_TIMECODE => PacketSideDataType::S12M_TIMECODE,
            ffi::AVPacketSideDataType::AV_PKT_DATA_DYNAMIC_HDR10_PLUS => PacketSideDataType::DYNAMIC_HDR10_PLUS,
            ffi::AVPacketSideDataType::AV_PKT_DATA_NB => PacketSideDataType::DataNb,
        }
    }
}

impl From<PacketSideDataType> for ffi::AVPacketSideDataType {
    fn from(value: PacketSideDataType) -> ffi::AVPacketSideDataType {
        match value {
            PacketSideDataType::Palette => ffi::AVPacketSideDataType::AV_PKT_DATA_PALETTE,
            PacketSideDataType::NewExtraData => ffi::AVPacketSideDataType::AV_PKT_DATA_NEW_EXTRADATA,
            PacketSideDataType::ParamChange => ffi::AVPacketSideDataType::AV_PKT_DATA_PARAM_CHANGE,
            PacketSideDataType::H263MbInfo => ffi::AVPacketSideDataType::AV_PKT_DATA_H263_MB_INFO,
            PacketSideDataType::ReplayGain => ffi::AVPacketSideDataType::AV_PKT_DATA_REPLAYGAIN,
            PacketSideDataType::DisplayMatrix => ffi::AVPacketSideDataType::AV_PKT_DATA_DISPLAYMATRIX,
            PacketSideDataType::Stereo3d => ffi::AVPacketSideDataType::AV_PKT_DATA_STEREO3D,
            PacketSideDataType::AudioServiceType => ffi::AVPacketSideDataType::AV_PKT_DATA_AUDIO_SERVICE_TYPE,
            PacketSideDataType::QualityStats => ffi::AVPacketSideDataType::AV_PKT_DATA_QUALITY_STATS,
            PacketSideDataType::FallbackTrack => ffi::AVPacketSideDataType::AV_PKT_DATA_FALLBACK_TRACK,
            PacketSideDataType::CBPProperties => ffi::AVPacketSideDataType::AV_PKT_DATA_CPB_PROPERTIES,
            PacketSideDataType::SkipSamples => ffi::AVPacketSideDataType::AV_PKT_DATA_SKIP_SAMPLES,
            PacketSideDataType::JpDualMono => ffi::AVPacketSideDataType::AV_PKT_DATA_JP_DUALMONO,
            PacketSideDataType::StringsMetadata => ffi::AVPacketSideDataType::AV_PKT_DATA_STRINGS_METADATA,
            PacketSideDataType::SubtitlePosition => ffi::AVPacketSideDataType::AV_PKT_DATA_SUBTITLE_POSITION,
            PacketSideDataType::MatroskaBlockAdditional => ffi::AVPacketSideDataType::AV_PKT_DATA_MATROSKA_BLOCKADDITIONAL,
            PacketSideDataType::WebVTTIdentifier => ffi::AVPacketSideDataType::AV_PKT_DATA_WEBVTT_IDENTIFIER,
            PacketSideDataType::WebVTTSettings => ffi::AVPacketSideDataType::AV_PKT_DATA_WEBVTT_SETTINGS,
            PacketSideDataType::MetadataUpdate => ffi::AVPacketSideDataType::AV_PKT_DATA_METADATA_UPDATE,
            PacketSideDataType::MPEGTSStreamID => ffi::AVPacketSideDataType::AV_PKT_DATA_MPEGTS_STREAM_ID,
            PacketSideDataType::MasteringDisplayMetadata => ffi::AVPacketSideDataType::AV_PKT_DATA_MASTERING_DISPLAY_METADATA,
            PacketSideDataType::DataSpherical => ffi::AVPacketSideDataType::AV_PKT_DATA_SPHERICAL,
            PacketSideDataType::DataNb => ffi::AVPacketSideDataType::AV_PKT_DATA_NB,
            PacketSideDataType::ContentLightLevel => ffi::AVPacketSideDataType::AV_PKT_DATA_CONTENT_LIGHT_LEVEL,
            PacketSideDataType::A53CC => ffi::AVPacketSideDataType::AV_PKT_DATA_A53_CC,
            PacketSideDataType::EncryptionInitInfo => ffi::AVPacketSideDataType::AV_PKT_DATA_ENCRYPTION_INIT_INFO,
            PacketSideDataType::EncryptionInfo => ffi::AVPacketSideDataType::AV_PKT_DATA_ENCRYPTION_INFO,
            PacketSideDataType::AFD => ffi::AVPacketSideDataType::AV_PKT_DATA_AFD,
            PacketSideDataType::PRFT => ffi::AVPacketSideDataType::AV_PKT_DATA_PRFT,
            PacketSideDataType::ICC_PROFILE => ffi::AVPacketSideDataType::AV_PKT_DATA_ICC_PROFILE,
            PacketSideDataType::DOVI_CONF => ffi::AVPacketSideDataType::AV_PKT_DATA_DOVI_CONF,
            PacketSideDataType::S12M_TIMECODE => ffi::AVPacketSideDataType::AV_PKT_DATA_S12M_TIMECODE,
            PacketSideDataType::DYNAMIC_HDR10_PLUS => ffi::AVPacketSideDataType::AV_PKT_DATA_DYNAMIC_HDR10_PLUS,
        }
    }
}